import { NextRequest } from 'next/server';
import prisma from '@/lib/prisma';
import { authenticateRequest, errorResponse, successResponse } from '@/lib/utils';
import { generateMonthlyInsights } from '@/lib/ai';

// GET /api/insights/monthly?month=YYYY-MM
// Fetch monthly insights from database (generated by cron job)
// If not found, generate on-demand (fallback)
export async function GET(request: NextRequest) {
  try {
    const payload = await authenticateRequest(request);
    if (!payload) {
      return errorResponse('Chưa đăng nhập', 401);
    }

    const { searchParams } = new URL(request.url);
    const monthParam = searchParams.get('month'); // Format: YYYY-MM

    if (!monthParam) {
      return errorResponse('Thiếu tham số month (định dạng: YYYY-MM)', 400);
    }

    // Validate month format
    const monthRegex = /^\d{4}-\d{2}$/;
    if (!monthRegex.test(monthParam)) {
      return errorResponse('Định dạng month không hợp lệ (cần: YYYY-MM)', 400);
    }

    // Try to fetch from database first
    const existingInsight = await prisma.monthlyInsight.findUnique({
      where: {
        userId_month: {
          userId: payload.userId,
          month: monthParam,
        },
      },
    });

    if (existingInsight) {
      // Return cached insight from database
      return successResponse({
        insight: existingInsight.insight,
        month: existingInsight.month,
        totalEntries: existingInsight.totalEntries,
        stats: {
          avgMood: existingInsight.avgMood,
        },
        cached: true,
        generatedAt: existingInsight.createdAt,
      });
    }

    // Fallback: Generate on-demand if not found in database
    console.log(`[API] Generating on-demand insight for ${monthParam}`);

    const [year, month] = monthParam.split('-').map(Number);
    const startDate = new Date(Date.UTC(year, month - 1, 1));
    const endDate = new Date(Date.UTC(year, month, 0));

    const entries = await prisma.dailyEntry.findMany({
      where: {
        userId: payload.userId,
        date: {
          gte: startDate,
          lte: endDate,
        },
      },
      orderBy: { date: 'asc' },
    });

    if (entries.length === 0) {
      return successResponse({
        insight: 'Bạn chưa có bản ghi nào trong tháng này. Hãy bắt đầu ghi chép cảm xúc để nhận được lời khuyên từ AI nhé! 💙',
        month: monthParam,
        totalEntries: 0,
        cached: false,
      });
    }

    // Generate AI insights
    const monthName = `Tháng ${month}/${year}`;
    const insight = await generateMonthlyInsights(entries, monthName);

    // Calculate stats
    const avgMood = entries.reduce((sum, e) => sum + e.moodScore, 0) / entries.length;

    // Save to database for future requests
    try {
      await prisma.monthlyInsight.create({
        data: {
          userId: payload.userId,
          month: monthParam,
          insight,
          totalEntries: entries.length,
          avgMood: parseFloat(avgMood.toFixed(2)),
        },
      });
    } catch (dbError) {
      console.error('[API] Failed to cache insight:', dbError);
      // Continue even if caching fails
    }

    return successResponse({
      insight,
      month: monthParam,
      totalEntries: entries.length,
      stats: {
        avgMood: parseFloat(avgMood.toFixed(2)),
      },
      cached: false,
    });
  } catch (error: any) {
    console.error('Generate insights error:', error);
    
    // Check if it's an AI-specific error
    if (error.message && error.message.includes('AI')) {
      return errorResponse(error.message, 503);
    }
    
    return errorResponse('Đã xảy ra lỗi khi tạo báo cáo', 500);
  }
}

// Handle OPTIONS for CORS
export async function OPTIONS() {
  return new Response(null, { status: 200 });
}
